model:
  name: "MLP"
  checkpoint_path: "/Users/karol/projects/ClothesSegmentation/mlruns/2/504da14d50b14b9a99fe76a19ac9e537/artifacts/model_checkpoint/last-v6.ckpt"
  input_size: 784  # (28 * 28)
  hidden_size: 128
  output_size: 10
  lr: 1e-3

  dataloaders_config:
    test:
      shuffle: False
      num_workers: 7
      batch_size: 32
      