max_epochs: 2
logger:
  experiment_name: "visualization_test"
  run_name: "mock model"
  checkpoint_dir: "mlcheckpoints"
  tracking_uri: "sqlite:///mlflow.db"

model:
  name: "Mock"
  lr: 1e-3

  dataset_config:
    name: "DeepFashionMask"
    root_path: "./data/DeepFashionMask"
    target_size_hw: [28, 28]
    subset: 10

  dataloaders_config:
    train:
      shuffle: True
      num_workers: 7
      batch_size: 2
      persistent_workers: True
    val:
      shuffle: False
      num_workers: 7
      batch_size: 2
      persistent_workers: True
