max_epochs: 2
precision: 32
logger:
  experiment_name: "mask_model"
  run_name: "cnn model test"
  checkpoint_dir: "mlcheckpoints"
  tracking_uri: "sqlite:///mlflow.db"

model:
  name: "CNN"
  lr: 1e-3

  dataset_config:
    name: "DeepFashionMask"
    root_path: "./data/DeepFashionMask"
    target_size_hw: [64, 64]
    subset: 10

  dataloaders_config:
    train:
      shuffle: True
      num_workers: 7
      batch_size: 2
      persistent_workers: True
    val:
      shuffle: False
      num_workers: 7
      batch_size: 2
      persistent_workers: True

visualization:
  save_path: "mlf_visualizations"
  image_size_hw: [512, 512]
  frames: [0, 1, 2]